workspace:
  base: /go
  path: src/github.com/Adaptech/letseventsource

pipeline:
  build:
    image: publysher/hugo:latest
    commands:
      - cd /go/src/github.com/Adaptech/letseventsource/docs && make build-web


